import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    ".vercel/**",
    "out/**",
    "build/**",
    "graphify-out/**",
    ".playwright-cli/**",
    ".scratch/**",
    // Generated by `supabase start`; CI starts the local stack before linting.
    "supabase/.temp/**",
    "next-env.d.ts",
    // Decoder binaries copied out of node_modules by scripts/copy-wasm.mjs.
    // Third-party Emscripten output — not ours to lint, and opencv.js alone is
    // 13MB on one line, which is minutes of pointless work per run.
    "public/wasm/**",
  ]),
]);

export default eslintConfig;
